### ISSUE TITLE
header parameter does not return request.headers 

### ISSUE THREAD

**Issue by rrr34** [luolingchun/flask-openapi3#10]
This is my code:

![image](https://user-images.githubusercontent.com/47373891/147398517-e8bb3742-6bd0-4115-82bf-65484402f9cc.png)

and this is the response:

![image](https://user-images.githubusercontent.com/47373891/147398542-469ddcd5-7e4e-47d6-aafb-b7fa58f4d0ea.png)
![image](https://user-images.githubusercontent.com/47373891/147398546-c018f6c8-d108-477c-93d3-d43b83aaf18c.png)
 

What is expected:

![image](https://user-images.githubusercontent.com/47373891/147398578-898414fa-e5a6-4983-97a6-3de457d5306c.png)

There is also this case:
 
 If I define my hello in Headers class as:
 
`hello: str = Field("what's up")`

then no matter what I place in my "hello" header, I always get the default "what's up" value.

![image](https://user-images.githubusercontent.com/47373891/147398649-3d897c5f-54e4-4997-a8ed-c529f3c052fb.png)

P.D. Thanks so much for this great library!

**Comment by luolingchun** [comment]
It is caused by the case of initial letters. I'll fix it.
