### ISSUE TITLE
Flask-sqlalchemy, Flask-migrate, psycopg3 weird behaviour

### ISSUE THREAD

**Issue by Saranthyr** [luolingchun/flask-openapi3#101]
Environment: venv

- Python version: 3.11
- Operating system: Windows 10
- Flask version: 2.3.2
- flask-openapi3 version: 2.4.0+

Weird behaviour of aforementioned modules with more recent versions of Flask-openapi3: upon trying to initiate db upgrade, psycopg3 connection raises `ResourceWarning` while migrating:

```
ResourceWarning: connection <psycopg.Connection [IDLE] (host=*** user=*** database=***) at 0x240928d4210> was deleted while still open. Please use 'with' or '.close()' to close the connection
```
Previous releases of flask-openapi3 (tested only on 2.3.2) doesn't seem to have such reaction whilst using same versions of psycopg3, sqlalchemy, flask-migrate and flask-sqlalchemy

**Comment by luolingchun** [comment]
Version 2.4.0+ adds a warning code, which is only a warning message and will not affect the result.

https://github.com/luolingchun/flask-openapi3/blob/v2.4.0/flask_openapi3/scaffold.py#L35

These warning codes will be removed in v3.0.
