### ISSUE TITLE
Shorthand way of describing that the response will be an array of items.

### ISSUE THREAD

**Issue by simonblund** [luolingchun/flask-openapi3#113]
`@api_view.doc(
        summary="List customers",
        responses={"200": List[Customer]},
    )`

Hi once again Luo!
I have come across the issue a couple of times now where I would have needed to respond with a list of defined items. I'm currently looking into putting it into a response dict, but a typeof List capability here would be greatly appreciated.

Like always, no need to stress about it. But I think it would be greatly appreciated.
Take care!

**Comment by luolingchun** [comment]
see #57
