### ISSUE TITLE
Every route gets a 422 response created

### ISSUE THREAD

**Issue by Danielsn1** [luolingchun/flask-openapi3#122]
When looking at the openAPI spec for a given route generated by flask-openapi3 every route has a 423 response object. Is this intentional behavior? If it is intentional behavior is there a way to remove it?

**Comment by luolingchun** [comment]
422 response is the default behavior after parameter validation fails, why would you remove it? 
Of course, you can change this default behavior (https://luolingchun.github.io/flask-openapi3/v2.x/Usage/Specification/#validation-error), but you can't remove it.

**Comment by Danielsn1** [comment]
If one of the routes that you want documented is a server health check that doesn't require a Pydantic model ex.

``` python
@api.get('/hello/<name>', tags=[health_check], responses={HTTPStatus.OK: {"content": { "text/text": { "schema": { "type": "string","example": example}}}})
def say_hello():
    return str(('Hello User!', 200))
```
It wouldn't make sense for there to be a 422 response generated because there is no input validation necessary, and there is no Pydantic model being used for validation.

**Comment by luolingchun** [comment]
I created a PR (#123 ) to fix this.
