### ISSUE TITLE
Optional null value with model_fields_set

### ISSUE THREAD

**Issue by fluffybrain3** [luolingchun/flask-openapi3#138]
Environment:

- Python version: 3.12
- Operating system: Windows 11
- Flask version: 3.0.0
- flask-openapi3 version: 3.0.1

That's the only way of declaring a field which will be:
1. Not required
2. Accepting null values

```python
from uuid import UUID

class PatchRequest(BaseModel):
    sth_id: Optional[UUID] = None
```

The problem is when you want to set this field in a PATCH request as null:
```json
{
    "sth_id": null
}
```

this if condition evaluates to false:
```python
if 'sth_id' in patch_request.model_fields_set:
    # do sth
```

In 2.x version of the flask-openapi3 it was possible to make it work, because the field declaration for such situation was different (without "= None").

So what I'm trying to achieve is a field which will be:
1. Not required
2. Accepting null values
3. Present in model_fields_set when it's value in the request is set as null

**Comment by luolingchun** [comment]
I can't seem to reproduce your issue. `body.model_fields_set` equals to `{'sth_id'}` in flask-openapi3 v2.x and v3.x.
```python
class PatchRequest(BaseModel):
    sth_id: Optional[UUID] = None


@app.patch("/book")
def patch_book(body: PatchRequest):
    print(body.model_fields_set)  # {'sth_id'}

    return "ok"
```

![image](https://github.com/luolingchun/flask-openapi3/assets/22740403/33341668-394f-4c72-8599-d45ab6556aa4)

**Comment by fluffybrain3** [comment]
Sorry, I actually meant sth different.
When you declare a field in this way

```python
from uuid import UUID

class PatchRequest(BaseModel):
    sth_id: Optional[UUID] = None
```

and your PATCH request won't contain this field at all, then it will be present in model_fields_set.
This means there is now no option to differentiate between provided and not provided value in the request for not required fields.
For example:
1. User wants in to set sth_id to some actual ID.
2. Then in another request, the user wants to set the ID to None
3. And then in a 3rd request, the user wants to set some other fields without specifying the sth_id field in the request at all, because it was not changed.
In the 3rd scenario, it's currently not possible to tell if the field was provided in the request or not.

**Comment by luolingchun** [comment]
Regardless of whether it is a v1 or a v2 version, `sth_id` in the `fields_set` absence does not depend on whether the "= None" part is declared or not, only whether the `sth_id` is passed or not.
You need to provide executable code examples, otherwise I can't figure out what the problem is.

```python
from typing import Optional
from uuid import UUID

from pydantic.v1 import BaseModel


class PatchRequestV1(BaseModel):
    sth_id: Optional[UUID]
    # There is no different
    # sth_id: Optional[UUID] = None


patch_request = PatchRequestV1()

print(patch_request.__fields_set__)

from pydantic import BaseModel


class PatchRequestV2(BaseModel):
    sth_id: Optional[UUID] = None


patch_request = PatchRequestV2()
print(patch_request.model_fields_set)
```
