### ISSUE TITLE
Missing Pydantic Calculated Fields From openapi.json

### ISSUE THREAD

**Issue by thebmw** [luolingchun/flask-openapi3#139]
When using calculated fields the field is not showing up in the output schema in the openapi.json file.

Environment:

- Python version: 3.12
- Operating system: Linux arm64
- Flask version: 3.0.0
- flask-openapi3 version: 3.0.1

**Comment by luolingchun** [comment]
Can you describe it in more detail? It's good to have code examples.

**Comment by thebmw** [comment]
I have added an simplified version of the model that caused me to notice the issue. I have implemented a possible fix [here](https://github.com/thebmw/flask-openapi3/blob/f21b26d2ee924832573d78ed52a44b1cf4b3c87a/flask_openapi3/utils.py) .

### Example Model
```python
class User(BaseModel):
    id: UUID = Field(title='Id', description='User Id for Human Users, Client Id for Machine Users')

    userType: UserType = Field(default=UserType.Human, title='User Type')

    firstName: str = Field(title='First Name')
    lastName: str
    email: str

    @computed_field(title='Display Name')
    @cached_property
    def displayName(self) -> str:
        match self.userType:
            case UserType.Human:
                return f'{self.firstName} {self.lastName}'
            case UserType.Machine:
                return f'{self.lastName}[{self.firstName}]'
            case _:
                raise NotImplementedError(f'Unsupported userType of {self.userType}')
```

**Comment by luolingchun** [comment]
@thebmw Can you submit a PR?

I agree with your solution, but I would rather accept adding a `mode='validation'` parameter to [get_model_schema](https://github.com/luolingchun/flask-openapi3/blob/master/flask_openapi3%2Futils.py#L119-L119) to change the value of mode to serialize the response model.
