### ISSUE TITLE
Swagger Validator Error when application is deployed

### ISSUE THREAD

**Issue by 12-Rishabh** [luolingchun/flask-openapi3#145]
Environment:

- Python version: 3.12
- Operating system: Windows
- Flask version: 3.0.2
- flask-openapi3 version: 3.0.2

I have created an application using this module and deployed it to an ECS container. After deployment when I access the Swagger-UI, an error image is displayed which is because swagger-validator is unable to access the file openapi/openapi.json for the validation.
Firms using this library have usually blocked access for outside APIs with their firewall. 
The only workaround to avoid this error is to pass a new swagger-html string through ui-template and set the parameter "validatorUrl" as null, which basically turns this validation off.
But just to change 1 parameter we have to create a complete file with html code repitition. 
So it would be great if we can expose the parameter "validatorUrl" in the module, like other parameters such as ui_template which can be passed while creating the app object.

**Comment by luolingchun** [comment]
I've submitted a PR (#146 ) to support this, adding `swagger_config` parameter to support all [Swagger Configuration](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md).

**Comment by 12-Rishabh** [comment]
Thanks for creating a PR for it! Will it be out in the next release? If yes when is the release date?

**Comment by 12-Rishabh** [comment]
I have tested the changes by deploying into ecs, and it was working fine! Thanks for fixing it. Can you please let me know when it will be released?
