### ISSUE TITLE
Release v4.0

### ISSUE THREAD

**Issue by luolingchun** [luolingchun/flask-openapi3#152]
About the changes in the v4.0 version:

- [x] #151 
- [x] Create [plugins repository](https://github.com/luolingchun/flask-openapi3-plugins) to manage more ui templates:
  - [x] [Swagger](https://github.com/swagger-api/swagger-ui)
  - [x] [Redoc](https://github.com/Redocly/redoc)
  - [x] [RapiDoc](https://github.com/rapi-doc/RapiDoc)
  - [x] [RapiPdf](https://mrin9.github.io/RapiPdf/)
  - [x] [Scalar](https://github.com/scalar/scalar)
  - [x] [Elements](https://github.com/stoplightio/elements)
- [x] #160 
- [x] #167
- [x] #174 

Some break changes:

- #161 
- Remove builtin ui templates, swagger redoc, rapidoc
- The `oauth_config` is deprecated in v4.x, use `app.config['OAUTH_CONFIG']` instead.
- The `doc_expansion` is deprecated in v4.x, use `app.config['SWAGGER_CONFIG']` instead.
- The `swagger_config` is deprecated in v4.x, use `app.config['SWAGGER_CONFIG']` instead.
- `api_doc_url` renamed to `doc_url` in `OpenAPI`
- Remove `swagger_url` in `OpenAPI`
- Remove `redoc_url` in `OpenAPI`
- Remove `rapidoc_url` in `OpenAPI`
- Remove `ui_templates` in `OpenAPI`

**Comment by luolingchun** [comment]
[v4.0.0rc2](https://pypi.org/project/flask-openapi3/4.0.0rc2/) has been released.

**Comment by devssauro** [comment]
One cool feature that could be added is the possibility to get the openapi spec file not just in JSON, but also in YAML.

**Comment by luolingchun** [comment]
@devssauro You can use `flask openapi -f yaml` get spec file in YAML.

More information about the command [flask openapi](https://luolingchun.github.io/flask-openapi3/v4.x/Usage/Specification/#command-flask-openapi).

Of course, if you cannot meet your needs, you can leave your thoughts behind.

**Comment by luolingchun** [comment]
[v4.0.0rc3](https://pypi.org/project/flask-openapi3/4.0.0rc3/) has been released.
