### ISSUE TITLE
With OpenApi Support base url for all flask api is not working

### ISSUE THREAD

**Issue by sreekesh93** [luolingchun/flask-openapi3#156]
Environment:

- Python version: 3.12
- Operating system: mac
- Flask version: 3.0.3
- flask-openapi3 version: 3.1.1
`

from flask_openapi3 import OpenAPI, APIBlueprint
from flask_openapi3 import Info
info = Info(title="example Service", version="1.0.0")
app = OpenAPI(__name__, info=info)
api = APIBlueprint('api', __name__, url_prefix='/api/v1')

@api.route("/answer",methods=['POST'])
def answer(body: RequestBody):
    return process(body)

app.register_api(llm_api)

`

with this piece of code I am not able to get the swagger doc but  I can hit answer endpoint from postman and response is received

**Comment by luolingchun** [comment]
`@api.route("/answer",methods=['POST'])` only inheriting the `route` function of Flask，please use `@api.post("/answer")` instead.
