### ISSUE TITLE
Default value is ignored for query parameters typed as lists

### ISSUE THREAD

**Issue by guillaume-alvarez** [luolingchun/flask-openapi3#174]
Environment:

- Python version: 3.12.3
- Operating system: ubuntu 22.04
- Flask version: 2.3.3
- flask-openapi3 version: 3.1.3

I defined a model with fields having default values like these ones:
```python
class ObjectQuery(BaseModel):
  order_by: list[str] = ["+creation", "+update"]
  status: list[ObjectStatus] = [ObjectStatus.NEW]
```
And use it as a query parameter in a route:
```python
@api.get("objects/", responses={HTTPStatus.OK: ObjectList})
def search_objects(query: ObjectQuery) -> Response:
```
The field correctly appear with their default values in the `openapi.json` file but when sending a query without any query parameter (as they all have default values) the instantiated `query` object fields are empty lists instead of the default values.

I checked the code and I found issue comes from [flask_openapi3.request._validate_query](https://github.com/luolingchun/flask-openapi3/blob/b073e03b5e4b5008b758175e9e4a8f4f35c44b3b/flask_openapi3/request.py#L36C1-L37C1). When the property is an array/list, the `value` set on line 41 is `[]`. So on line 44 the check `if value is not None:` is true and line 45 `query_dict[k] = value` set the value to `[]`. It leads to pydantic loading the value `[]` instead of its default value.

Is there an error in the way I define the default values?

Or is it a bug in flask_openapi3?
I guess it could check `if value is not None:` but maybe there is a valid usecase for clients to set explicitly an empty list or string or 0?
Or befure the `request_args.getlist()` a simple `request_args.get()` should be performed to check the value is present?

**Comment by luolingchun** [comment]
Thank you for the report.

I think further judging whether the value is an empty array or not will solve the problem.

```diff
def _validate_query(query: Type[BaseModel], func_kwargs):
    request_args = request.args
    query_dict = {}
    for k, v in query.model_fields.items():
        if get_origin(v.annotation) is list:
            value = request_args.getlist(v.alias or k) or request_args.getlist(k)
        else:
            value = request_args.get(v.alias or k) or request_args.get(k)  # type:ignore
-        if value is not None:
+        if value is not None and value != []:
            query_dict[k] = value
    func_kwargs["query"] = query.model_validate(obj=query_dict)
```

I've been a little busy lately and would like you to have time to submit a PR with unit tests.

**Comment by guillaume-alvarez** [comment]
I tried to run the unit tests following the CONTRIBUTING.md but they fail with errors like
```
E   TypeError: __get_pydantic_core_schema__() takes 2 positional arguments but 3 were given
```
when loading test classes like this one:
```
class BookForm(BaseModel):
    file: FileStorage
    files: List[FileStorage]
    string: str
    string_list: List[str]
```
