### ISSUE TITLE
Setting an example value for a field in query object generates deprecation warnings with pydantic >= 2.8

### ISSUE THREAD

**Issue by guillaume-alvarez** [luolingchun/flask-openapi3#177]
Environment:

- Python version: 3.12.3
- Operating system: Ubuntu 
- Flask version: 2.3.3
- flask-openapi3 version: 3.1.3

/!\ This issue is similar to https://github.com/luolingchun/flask-openapi3/issues/176 but this time for a model used in a query

## Warning

If I define a model setting `Field.example` (not defined in pydantic):
```python
class Query(BaseModel):
    stream_id: str = Field(..., example="test_stream")
```
then it causes warnings because it is not officially supported by pydantic:
```
PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
```

## Crash

If I define a model setting the `Field.examples` [as advised by pydantic](https://docs.pydantic.dev/2.9/concepts/json_schema/#field-level-customization):
```python
class Query(BaseModel):
    stream_id: str = Field(..., examples="test_stream")
```
Then it crashes the application:
```
  File "/project/.venv/lib/python3.12/site-packages/flask_openapi3/scaffold.py", line 163, in decorator
    self._collect_openapi_info(
  File "/project/.venv/lib/python3.12/site-packages/flask_openapi3/blueprint.py", line 181, in _collect_openapi_info
    header, cookie, path, query, form, body, raw = parse_parameters(
                                                   ^^^^^^^^^^^^^^^^^
  File "/project/.venv/lib/python3.12/site-packages/flask_openapi3/utils.py", line 458, in parse_parameters
    _parameters, _components_schemas = parse_query(query)
                                       ^^^^^^^^^^^^^^^^^^
  File "/project/.venv/lib/python3.12/site-packages/flask_openapi3/utils.py", line 246, in parse_query
    parameters.append(Parameter(**data))
                      ^^^^^^^^^^^^^^^^^
  File "/project/.venv/lib/python3.12/site-packages/pydantic/main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Parameter
examples
  Input should be a valid dictionary [type=dict_type, input_value='test_stream', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/dict_type
```

This field was added in pydantic 2.5.0 by https://github.com/pydantic/pydantic/pull/8013

Debugging the code I see that `flask_openapi3.utils.parse_query` will try to parse the examples value as an `Optional[Dict[str, Union[Example, Reference]]] `, which seems in line with the [OpenAPI 3.1.0 spec](https://spec.openapis.org/oas/v3.1.0#fixed-fields-9). Maybe some conversion could be made in `flask_openapi3.utils.parse_query` to support a list[str] example that is valid in pydantic?

**Comment by luolingchun** [comment]
OpenAPI and pydantic have completely different definitions for examples, so they can't be mixed.


OpenAPI-[Parameter Object](https://spec.openapis.org/oas/v3.1.0#parameter-object):

![image](https://github.com/user-attachments/assets/7d3a053c-b781-4336-bb8e-73ae571f63a3)

Pydantic-[Field](https://docs.pydantic.dev/2.9/api/fields/#pydantic.fields.Field):

![image](https://github.com/user-attachments/assets/cba07054-90c7-444e-abf4-e3c457400303)

In fact, Flask-openapi3 already supports customizing the `examples` field, please refer to the [documentation](https://luolingchun.github.io/flask-openapi3/v4.x/Usage/Model_Config/#openapi_extra).

**Comment by guillaume-alvarez** [comment]
Thanks for the explanation.
