### ISSUE TITLE
ServerVariable.enum should be optional

### ISSUE THREAD

**Issue by Soremwar** [luolingchun/flask-openapi3#188]
Per https://spec.openapis.org/oas/v3.1.0#fixed-fields-4, `enum` is An enumeration of string values to be used if the substitution options are from a limited set. The array MUST NOT be empty.

I think this was interpreted as enum being a required property, when in reality it's optional and treating it as such removes the ability for applications to set the specificied variables with an arbitrary value

Without `enum`:
![image](https://github.com/user-attachments/assets/0def08d6-5ccd-4ee4-a84c-4454949e1e53)

With `enum`:
![image](https://github.com/user-attachments/assets/31f34e6d-40a0-4927-89ac-d5a619777a8f)

**Comment by luolingchun** [comment]
Thanks for your report, I will fix it.
