### ISSUE TITLE
Question: Use of components / references / parameters

### ISSUE THREAD

**Issue by brownterryn** [luolingchun/flask-openapi3#192]
Looking at switching from flasgger to flask-openapi3

The way I have things set up using flasgger (with @swag_from to read yaml specs.) I can generate an OpenAPI spec. which uses components/parameters and references, so an endpoint's spec. might look like:

<details>
<summary>example JSON endpoint spec.</summary>

```json
"/some-api/api/v4/chemNN/": {
    "get": {
        "description": "Get nearest neighbors for chem. with FP",
        "responses": {
              "200": {
                   "description": "Nearest neighbors and FP or chem."
              }
         },
        "parameters": [
            {"$ref": "#/components/parameters/chem_id"},
            {"$ref": "#/components/parameters/fp"},
            {"$ref": "#/components/parameters/fp_weight"},
            {"$ref": "#/components/parameters/sel_by"},
            {"$ref": "#/components/parameters/k0"}
        ],
    "tags": [
       "domain"
     ]
  }
}
```

</details>

Can flask-openapi3 generate output like that?  I see the Components and Parameters models, but not sure how to use them.

**Comment by luolingchun** [comment]
`flask-openapi3` doesn't use an explicit spec like `flasgger`, which you can get using http://127.0.0.1:5000/openapi/openapi.json.

More information see the [Specification](https://luolingchun.github.io/flask-openapi3/v4.x/Usage/Specification/#specification).
