### ISSUE TITLE
Add support for Blueprint.route()

### ISSUE THREAD

**Issue by DerManoMann** [luolingchun/flask-openapi3#2]
While I am at it ...

The application I am working on makes extensive use of the blueprint `route()` method, so adding support for that in `APIBlueprint` would make a potential integration at lot easier.

Thanks for all the work!

**Comment by luolingchun** [comment]
`APIBlueprint` inherited from `Blueprint`, so i think you can use the `route()` method directly .

but it doesn't work for swagger...

**Comment by DerManoMann** [comment]
Yes, that is the point. I am not quite sure what the difference is between `route()` and individual methods like `get()`, but I suppose it should be possible to override it in `APIBlueprint`?
That would also avoid having to refactor in cases where an endpoint supports more than one HTTP methods...

**Comment by luolingchun** [comment]
This library focuses more on RESTful APIs and OpenAPI docs.

**Comment by DerManoMann** [comment]
I am sorry, this answer doesn't make sense to me. Why is that different for OpenAPI docs whether a route is registered my `route()` vs. `get()`? (As mentioned, I am not clear about the difference between the two, but both can server JSON, XML or whatever and can support different auth schemes...?)

**Comment by DerManoMann** [comment]
I did some more digging. The API docs state that `get()` is a shortcut for `route()` with `methods=["GET"]`
From: https://flask.palletsprojects.com/en/2.0.x/api/#flask.Blueprint.get

**Comment by luolingchun** [comment]
We can make it for swagger. But if you specify two HTTP methods in `route()`(e.g. GET, POST), you'll get two API in swagger with same parameters，it feels weird.

I think `get` for query resources and `post` for created . Why don't we use `get` and `post` separately to make things easier?

**Comment by martinatseequent** [comment]
Fair enough.
