### ISSUE TITLE
FastAPI like "root_path" for swagger beind the proxy

### ISSUE THREAD

**Issue by tokwiat** [luolingchun/flask-openapi3#206]
Environment: 

- Python version: 3.9
- Operating system: Azure Cloud
- Flask version: 3.0.3
- flask-openapi3 version: 4.0.3
- flask-openapi3-swagger: 5.18.2

Hey, is there a way to provide "root_path" or any other arg for swagger UI to correctly resolve API that is behind proxy (url has some prefix before "/") which is configured in Azure Cloud? 

This is related article for FastAPI and it's swagger config:
https://fastapi.tiangolo.com/advanced/behind-a-proxy/

**Comment by luolingchun** [comment]
In fact, `Flask` has [`root_path`](https://flask.palletsprojects.com/en/stable/api/#flask.Flask.root_path) variables, but they serve a very different purpose than `FastAPI`, but the same variable [`url_prefix`](https://flask.palletsprojects.com/en/stable/api/#flask.blueprints.BlueprintSetupState.url_prefix) as `FastAPI` is provided in the `Blueprint` with the `root_path` functionality.

**Comment by tokwiat** [comment]
> In fact, `Flask` has [`root_path`](https://flask.palletsprojects.com/en/stable/api/#flask.Flask.root_path) variables, but they serve a very different purpose than `FastAPI`

Correct! Cannot be used here though.

> but the same variable [`url_prefix`](https://flask.palletsprojects.com/en/stable/api/#flask.blueprints.BlueprintSetupState.url_prefix) as `FastAPI` is provided in the `Blueprint` with the `root_path` functionality.

This not exactly the case, so  `Blueprint` is adding prefix to the endpoints themself, explicitly, eg.:

`api = APIBlueprint('/subscribe', __name__, url_prefix='/subscribe')`

is ending with direct extension of all endpoints with '/subscrbe' prefix like this:
![Screenshot 2024-12-02 at 21 25 54](https://github.com/user-attachments/assets/475921e0-43e2-43af-bbf8-1394e41d126a)

What I want to achieve is something like this:
![Screenshot 2024-12-02 at 21 33 18](https://github.com/user-attachments/assets/ff4f797b-2fbd-4ac4-a099-c528964e2082)


This way swagger UI (and openapi spec)  "does know" about the "proxy" (hidden url part) that is configured for the cloud deployment and still saves the original paths for endpoints.
So this way swagger UI will behave as it does for FastAPI config. This is the hackfix I did, wonder if we can make it more user friendly:
`app.api_doc.update(servers=[{"url": "/subscribe"}])`

I can make a PR to introduce this one, if needed, to be present as an arg to pass to app.

**Comment by luolingchun** [comment]
The `root_path` in `FastAPI` is implemented by `ASGI`, I did not find an implementation related to `WSGI`.

I'm curious how you can do it, and feel free to submit a PR.

**Comment by tokwiat** [comment]
Hey, this can be closed. There's a way to configure this one by setting servers attr.
