### ISSUE TITLE
Use `defer_build` for faster Model init

### ISSUE THREAD

**Issue by ddorian** [luolingchun/flask-openapi3#209]
Environment:

- Python version: 3.12
- Operating system: Ubuntu 22.04
- Flask version: 3.1.0
- flask-openapi3 version: 4.0.1

On a simple profile of imports in my app, the models of pydantic in this package take ~0.13s (besides pydantic import).
Consider using https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.defer_build ?

**Comment by luolingchun** [comment]
@ddorian Can you do a test and how much you can improve?

**Comment by ddorian** [comment]
Using the commit below I was only able to remove ~20ms. So 0.13s -> 0.11s. On pydantic 2.10.3. 

Commit: https://github.com/ddorian/flask-openapi3/commit/c7938c5fd296bcf7f3fc8963eb66efdbc03448e9

**Comment by luolingchun** [comment]
20ms doesn't seem to be of much use, waiting for `pydantic` to support `defer_build` by default.
