### ISSUE TITLE
dead mkdoc Plugin i18n

### ISSUE THREAD

**Issue by schoekek** [luolingchun/flask-openapi3#210]
It seems that the i18n mkdocs plugin is dead, can you switch to mkdocs-static-i18n?
I want to package your project for Debian...

**Comment by luolingchun** [comment]
This library has been using `mkdocs-static-i18n` all along, do you need any questions?

https://github.com/luolingchun/flask-openapi3/blob/master/requirements/doc.txt#L1

**Comment by schoekek** [comment]
Sorry, I thought that
https://github.com/luolingchun/flask-openapi3/blob/master/mkdocs#L57
referred to
https://pypi.org/project/mkdocs-i18n/.
I had overlooked the references file.
The same namespace seems to be in use here.
