### ISSUE TITLE
Add support to protect the spec endpoint

### ISSUE THREAD

**Issue by DerManoMann** [luolingchun/flask-openapi3#3]
There is already a flag to disable the UI. In addition it would be nice to be able to somehow protect/control access to the spec endpoint itself.
Alternative, the ability to easily write the spec to a file on the command line (and a way to disable the openapi blueprint altogether) could work too...

**Comment by luolingchun** [comment]
I will consider adding `doc_ui` to endpoint and APIBlueprint

**Comment by mojimi** [comment]
@luolingchun can you give an example of how to serve the API docs from this dict? Looks like the templating logic is not exposed as a helper method

**Comment by luolingchun** [comment]
@mojimi I don't understand what you want. But the document is [here](https://luolingchun.github.io/flask-openapi3/v2.x/Tutorial/Specification/#doc_ui) about `doc_ui`.

**Comment by mojimi** [comment]
> @mojimi I don't understand what you want. But the document is [here](https://luolingchun.github.io/flask-openapi3/v2.x/Tutorial/Specification/#doc_ui) about `doc_ui`.

Yes, thank you, but that isn't enough to add custom logic to the UI routes to be able to put it under a secured endpoint

For example, proposed new methods:

```python
# views/docs.py
@app.get('/openapi/swagger')
@my_auth_decorator
    return app.render_openapi_template('swagger')

# Or, alternatively:
# __init__.py
app = flask_openapi3.OpenAPI(__name__, template_folder='templates', before_request=my_auth_decorator)
```

**Comment by luolingchun** [comment]
@mojimi Here are a few examples that I hope can help you.

https://github.com/luolingchun/flask-api-demo/blob/master/src/app/api/book.py
