### ISSUE TITLE
Support for other JSON libraries?

### ISSUE THREAD

**Issue by diogobaeder** [luolingchun/flask-openapi3#31]
Environment:

- Python version: 3.9
- Operating system: Arch Linux
- Flask version: 2.1.2
- flask-openapi3 version: 2.0.0

Hi there! Congratulations, this is a remarkable library and it's helping me a lot to get my Flask-based app documented with OpenAPI.

Let me ask something though: is there any plan to allow different JSON to be used for data serialization, like `orjson` or `ujson`? I'm asking because for larger amounts of data they make a lot of difference in performance compared to the stdlib `json` module.

Thanks!

**Comment by luolingchun** [comment]
This seems to have the same problem in Flask [#1793](https://github.com/pallets/flask/issues/1793).

I'm not sure whether there is a way to use `ujson` or `orjson` to implement '`app.json_decoder`.

**Comment by diogobaeder** [comment]
Interesting. Well, for the time being, I'm building the response object myself, encoding with `orjson`, so I hope some day we can have that implemented too. I was wondering if it would be possible for `flask-openapi3` itself to handle that though, so that for larger response payloads the performance improvement could be more significant.

**Comment by luolingchun** [comment]
Since flask 2.2.0, the json provider has been supported, so we can use `orjson` or `ujson`.

I did a simple test.

orjson
```python
import orjson
from flask.json.provider import JSONProvider


class OrJSONProvider(JSONProvider):
    # https://github.com/ijl/orjson#option
    option = orjson.OPT_INDENT_2

    def dumps(self, obj, **kwargs):
        return orjson.dumps(obj, option=self.option).decode()

    def loads(self, s, **kwargs):
        return orjson.loads(s)
    
app = OpenAPI(__name__, info=info)
# use orjson
orjson_provider = OrJSONProvider(app)
app.json = orjson_provider
```

ujson
```python
import ujson
from flask.json.provider import JSONProvider

class UJSONProvider(JSONProvider):
    # https://github.com/ultrajson/ultrajson
    encode_html_chars = False
    ensure_ascii = False
    indent = 4

    def dumps(self, obj, **kwargs):
        option = {
            "encode_html_chars": self.encode_html_chars,
            "ensure_ascii": self.ensure_ascii,
            "indent": self.indent
        }
        return ujson.dumps(obj, **option)

    def loads(self, s, **kwargs):
        return ujson.loads(s)
    
    
app = OpenAPI(__name__, info=info)
# use ujson
ujson_provider = UJSONProvider(app)
app.json = ujson_provider
```

**Comment by luolingchun** [comment]
Now I close this issue, you can reopen it at any time.
