### ISSUE TITLE
extra_responses are requiring content key (and only keeping content)

### ISSUE THREAD

**Issue by Colin-b** [luolingchun/flask-openapi3#35]
According to the [OpenAPI specification](https://spec.openapis.org/oas/v3.0.3#fixed-fields-14), content is not a required key within a response. However current code is requiring content to add an extra response: https://github.com/luolingchun/flask-openapi3/blob/71c4ca9ef17a0b5b82c865d5a8f1c7c37fef72c3/flask_openapi3/utils.py#L297

And it also assume that extra_responses only contains content, discarding provided description, headers and links.

extra_responses is currently the only way to describe responses not containing a body (ie: HTTP 201 / HTTP 204) and thus should allow to set any information OpenAPI specification allow in a response.

Please tell me if you want me to draft a pull request for this bug fix / enhancement.

Thanks again

**Comment by luolingchun** [comment]
Welcome PR.

**Comment by Colin-b** [comment]
PR is #37
