### ISSUE TITLE
How can I provide examples

### ISSUE THREAD

**Issue by Colin-b** [luolingchun/flask-openapi3#36]
According to [OpenAPI specification](https://spec.openapis.org/oas/v3.0.3#media-type-object), the media type object is the place to provide examples. However those informations are not part of the representation in project: https://github.com/luolingchun/flask-openapi3/blob/71c4ca9ef17a0b5b82c865d5a8f1c7c37fef72c3/flask_openapi3/models/common.py#L63

Even if they were, I wonder how they could be provided, what would be your approach with this?
Some thoughts: extra information on the pydantic model, an additional extra_body parameter, etc...

**Comment by luolingchun** [comment]
> Some thoughts: extra information on the pydantic model, an additional extra_body parameter, etc...

If we use pydantic model, during deserialization, extra_body parameter will also be resolved. This seems to be wrong.

I have an idea:

we can add `form_examples` and `body_examples` into app decorator. like this:

```python
def get(
        self,
        rule: str,
        *,
        tags: Optional[List[Tag]] = None,
        summary: Optional[str] = None,
        description: Optional[str] = None,
        responses: OpenAPIResponsesType = None,
        extra_responses: Optional[Dict[str, dict]] = None,
        form_examples: Optional[Dict[str, dict]] = None,
        body_examples: Optional[Dict[str, dict]] = None,
        security: Optional[List[Dict[str, List[Any]]]] = None,
        deprecated: Optional[bool] = None,
        operation_id: Optional[str] = None,
        doc_ui: bool = True,
        **options: Any
) -> Callable:
        ...
```
```python
examples={
      "chinese" : {
        "summary": "An example of a chinese",
        "value": 
          {
            "author": "chinese",
            "age": "12"
          }
      },
      "english" : {
        "summary": "An example of a english",
        "value": 
          {
            "author": "english",
            "age": "15"
          }
      }
    }


@app.post('/book', body_examples=examples)
def get_books(body: BookQuery):
    """get books
    get all books
    """
    print(query)
    return {"code": 0, "message": "ok"}
```

**Comment by Colin-b** [comment]
Yeah that would do it nicely, do you want me to draft a PR on this ?

**Comment by luolingchun** [comment]
Welcome and thanks.

**Comment by Colin-b** [comment]
Added in #38

**Comment by luolingchun** [comment]
@Colin-b I learned more about [Request Body Object](https://spec.openapis.org/oas/v3.0.3#request-body-object) and [Parameter Object](https://spec.openapis.org/oas/v3.0.3#parameter-object).

So i renamed `body_examples` to `extra_body` to customize more fields. 
For **Request Body Object**, i created a class `ExtraRequestBody`:
```python
class ExtraRequestBody(BaseModel):
    description: Optional[str] = None
    required: Optional[bool] = None
    # For MediaType
    example: Optional[Any] = None
    examples: Optional[Dict[str, Union[Example, Reference]]] = None
    encoding: Optional[Dict[str, Encoding]] = None
```
For **Parameter Object**, i created a class `ExtraParameter`:
```python
class ExtraParameter(BaseModel):
    deprecated: Optional[bool] = None
    allowEmptyValue: Optional[bool] = None
    # Serialization rules for simple scenarios
    style: Optional[StyleValues] = None
    explode: Optional[bool] = None
    allowReserved: Optional[bool] = None
    example: Optional[Any] = None
    examples: Optional[Dict[str, Union[Example, Reference]]] = None
    # Serialization rules for more complex scenarios
    content: Optional[Dict[str, MediaType]] = None
```
Now we can use it like this:
```python
extra_body = ExtraRequestBody(
    description="This is post RequestBody",
    required=True,
    example="ttt",
    examples={
        "example1": Example(
            summary="example summary1",
            description="example description1",
            value={
                "age": 24,
                "author": "author1"
            }
        ),
        "example2": Example(
            summary="example summary2",
            description="example description2",
            value={
                "age": 48,
                "author": "author2"
            }
        )
    }
)


@app.post('/book', tags=[book_tag], responses={"200": BookResponse}, extra_body=extra_body)
def create_book(body: BookBody):
    ...
```


I want you know this and I'll finish the `extra_form`, `extra_path`, `extra_query`, `extra_header`, `extra_cookie`.

**Comment by Colin-b** [comment]
Would it be possible to provide a dict instead? That way you can provide a dictionary without the need to import flask_openapi3 to describe an endpoint. If it's mandatory to provide pydantic models, as long as they are exposed as part of flask_openapi3 root i'm fine with it (that way you can change the internal file holding the definition without breaking changes for your clients).

Those are good addition, do you do the extra validation step on the required parameter for the body then?
