### ISSUE TITLE
Remove validate response before return [Breaking Changes]

### ISSUE THREAD

**Issue by luolingchun** [luolingchun/flask-openapi3#39]
Improve performance and keep it easy

**Comment by ddorian** [comment]
Looks like this validated the response schema was correct and now it's no longer validated, correct?

**Comment by luolingchun** [comment]
yes!

**Comment by mr-tabasco** [comment]
Were things really that slow when `FLASK_OPENAPI_VALIDATE_RESPONSE` was set to `False`?  Shame it's gone, this could be handy when doing regression tests on big systems or when developing new endpoints.

**Comment by ddorian** [comment]
Yes it should've at least been optional.

**Comment by mr-tabasco** [comment]
Assuming when it's switched off it doesn't cause performance issues, any chance this could come back? AFAIK FastAPI has this feature on by default and you can't switch it off, but could be wrong I've never gone past the tutorial with FastAPI and that was a while ago
