### ISSUE TITLE
Latest release dropped the required=True on request body by default

### ISSUE THREAD

**Issue by Colin-b** [luolingchun/flask-openapi3#41]
I can set it back to True thanks to the new extra_body argument.

The default value is supposed to be False in case it is not provided according to [OpenAPI specifications](https://spec.openapis.org/oas/v3.0.3#fixed-fields-10) but the code is actually expecting it to be provided.

IMO it should be considered as required by default in the code, set to required by default in the generated OpenAPI. However setting it to None or False should allow body not to be provided (set to None then when received in the endpoint).

**Comment by luolingchun** [comment]
I agree very much!
