### ISSUE TITLE
async routes not working

### ISSUE THREAD

**Issue by btcorgtfo** [luolingchun/flask-openapi3#48]
hi,

unfortunately `async def` routes are not working with an

`app = OpenAPI(__name__)`

simple route which should work

```
@app.get("/async_test")
async def async_test():
    return "hi"
```

if i change to `app = Flask(__name__)` the route returns "hi".

any chance this is only a small issue, so async routes can be used with OpenAPI3?

**Comment by luolingchun** [comment]
Currently, the async api is not supported. I will add support in the next version.

**Comment by btcorgtfo** [comment]
should have checked this single open PR first before complaining. Thanks!
