### ISSUE TITLE
`flask openapi` command not available

### ISSUE THREAD

**Issue by candleindark** [luolingchun/flask-openapi3#63]
Environment:

- Python version: 3.9.16
- Operating system: MacOS 13.3
- Flask version: 2.2.3
- flask-openapi3 version: 2.3.2

The `flask openapi` command mentioned in the documentation, https://luolingchun.github.io/flask-openapi3/Tutorial/Specification/#command-flask-openapi, is not available.

**Comment by GitCodeBoi1654** [comment]
wouldn't you be able to import flask and openAI seperately

**Comment by GitCodeBoi1654** [comment]
it might just be ur pc

**Comment by candleindark** [comment]
> it might just be ur pc

I ran the command in a virtual environment. How can that be the case?

**Comment by luolingchun** [comment]
You can use `--app` in command or use `app.py` or `wsgi.py`

```bash
flask --app simple_demo openapi
```

The following information is excerpted from https://flask.palletsprojects.com/en/2.2.x/quickstart/#a-minimal-application

---
To run the application, use the flask command or python -m flask. You need to tell the Flask where your application is with the --app option.

```
$ flask --app hello run
 * Serving Flask app 'hello'
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
```

Application Discovery Behavior

As a shortcut, if the file is named app.py or wsgi.py, you don’t have to use --app. See [Command Line Interface](https://flask.palletsprojects.com/en/2.2.x/cli/) for more details.

---

**Comment by candleindark** [comment]
@GitCodeBoi1654 
No worries. Thanks for trying to help.
