### ISSUE TITLE
Feature Request - allow initialization variables in register_api_view

### ISSUE THREAD

**Issue by simonblund** [luolingchun/flask-openapi3#66]
Hi!
Thank you for your great project, if I get time I'll try to come up with a PR for this feature.

In flask classful you had the option of adding initialization arguments to the view classes. As someone that comes from a DDD and DI background this is something I really want to do. It enables me to achieve poor man's Dependency Injection.
https://flask-classful.teracy.org/#well-more-words-on-register

`app.register_api_view(v1_template_rest.api_view, some_init_argument="ABC123")`

and in the api view:
```
@api_view.route("/example")
class ExampleApiView
    some_init_argument: str
    def __init__(self, some_init_argument:str):
        self.some_init_argument = some_init_argument
        
   def get():
       ....

```

**Comment by luolingchun** [comment]
Look good. Welcome PR!
