### ISSUE TITLE
Feature Request - custom get_operation_id_for_path handler

### ISSUE THREAD

**Issue by BoyanYK** [luolingchun/flask-openapi3#67]
Hi, thank you for your great work on this project!

I encountered a use case for being able to define custom handlers for generating the OpenAPI operation_id. 
In a large api, where we are adding `flask-openapi` we run into situations where a method like:
```python
@api.post("/logout", tags=[auth], ...)
def logout():
  ..
```
 The current `get_operation_id_for_path` handler generates an operation_id as: `logout_logout_post`. Then, when generating a client library with https://openapi-generator.tech/ it creates the following library usage (JS example):
 ```js
client.auth.logoutLogoutPost()
...
```
Which is just not that nice to use. Of course, this can be defined by setting `operation_id` on the endpoint but that means custom setting it for every endpoint.

I believe it would make sense to support adding a custom handler when creating `Blueprint` / `View` / `OpenAPI` instance. 

I would have time this week to open a PR for this feature, though I would also ask for advice on the following:
* What should the name for such a property be? Something like `operation_id_callback` perhaps?
* Would it be alright to also open a PR to make this change for `Flask-OpenAPI3` v1.x as maybe a small update to v1.1.4? We are still (unfortunately) currently using Flask 1.x so this would be quite important

**Comment by luolingchun** [comment]
Welcome PR!

I have checked out the `v1.x` branch from the `master` branch and made some preparations.

What I want you to know is that the new features and bug fixes in `v2.x` will not return to `v1.x`.

You can submit a PR to the `v1.x` branch, but I would like you to submit another PR to the `master` branch so that you can still use it when upgrading to `v2.x`.

**Comment by luolingchun** [comment]
release [v1.1.5](https://github.com/luolingchun/flask-openapi3/releases/tag/v1.1.5)
