### ISSUE TITLE
Feature request - Optiona to add top-level extensions to openapi spec

### ISSUE THREAD

**Issue by simonblund** [luolingchun/flask-openapi3#70]
Use case:
- Different API gateway providers (AWS API Gateway, Google API GATEWAY) needs extensions in their openapi-spec to be able to function.

Requirement from Google API Gateway: https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#x-google-backend (This gateway needs the OAS3 to be converted to OAS2 if someone comes here looking for help with that specific issue I recommend https://github.com/LucyBot-Inc/api-spec-converter in a GH action)

OpenAPI3 supports it: https://spec.openapis.org/oas/v3.0.3#specification-extensions

@luolingchun I will probably not have time to come up with a PR for this in the near future and will do a work around for my use case.

**Comment by luolingchun** [comment]
I agree to add specification extensions support, but I think the conversion from OAS3 to OAS2 should be implemented by the user themselves.

Additionally, I believe that google cloud will support OAS3 in the future.

https://issuetracker.google.com/issues/78271318


There are many objects(like, OpenAPI, Components, Operation,Request Body, Responses, Schema,  and more...) that support [Specification Extensions](https://spec.openapis.org/oas/v3.0.3#specification-extensions), and I have no idea to implement those objects.

I noticed that [FastAPI](https://fastapi.tiangolo.com/advanced/path-operation-advanced-configuration/?h=extensions#openapi-extensions) only implements Specification Extensions in [Operation](https://spec.openapis.org/oas/v3.0.3#operation-object).

@simonblund I don't have any experience using Google Cloud. What do you want to implement about Specification Extensions?

**Comment by luolingchun** [comment]
I will implement Specification Extensions in [OpenAPI Object](https://spec.openapis.org/oas/v3.0.3#openapi-object) and [Operation Object](https://spec.openapis.org/oas/v3.0.3#operation-object).

demo:

```python
from flask_openapi3 import OpenAPI

openapi_extensions = {
    "x-google-endpoints": [
        {
            "name": "my-cool-api.endpoints.my-project-id.cloud.goog",
            "allowCors": True
        }
    ],
    "x-google-backend": {
        "address": "https://<NODE_SERVICE_ID>-<HASH>.a.run.app",
        "protocol": "h2"
    }
}

app = OpenAPI(__name__, openapi_extensions={"x-google-endpoints": openapi_extensions["x-google-endpoints"]})


@app.get("/books", openapi_extensions={"x-google-backend": openapi_extensions["x-google-backend"]})
def get_book():
    ...
```

**Comment by simonblund** [comment]
That looks awesome!! :D
