### ISSUE TITLE
Enable sponsoring on the project

### ISSUE THREAD

**Issue by simonblund** [luolingchun/flask-openapi3#71]
Open Source projects are great. But we all know the effort that goes into keeping things going. People that don't have the time to contribute in code might want to contribute to the maintainers in other ways, GitHub Sponsorships is an easy way to do that.

**Comment by luolingchun** [comment]
@simonblund Keep free. GitHub Sponsor is not available in my country.

If there are other internationally accepted sponsorship methods, I would be happy to accept them.
