### ISSUE TITLE
Working for v3.0

### ISSUE THREAD

**Issue by luolingchun** [luolingchun/flask-openapi3#74]
- [x] Upgrade pydantic to v2.
- [x] Switch to pyproject.toml.
- [x] #91
- [ ] ~~Remove `**kwargs`( in `OpenAPI` and `APIBlueprint`) and replace it with specific parameters, see class [Flask](https://github.com/pallets/flask/blob/main/src/flask/app.py#L92) and class [Blueprint](https://github.com/pallets/flask/blob/main/src/flask/blueprints.py#L119).~~
- [ ] ~~Remove `**options`(in APIScaffold's get, post, put ... )  and replace it with specific parameters, see class [Rule](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/routing/rules.py#L312) in [werkzeug](https://github.com/pallets/werkzeug).~~
- [x] #92
- [x] #93

**Comment by samuelhwilliams** [comment]
Hey 👋  Really interested in seeing this release made available (mostly for the upgrade to pydantic v2 which allows custom `field_validators`). Just wondering if you have any timeline for when this might go out? I understand that it's probably a lot of work though :)

**Comment by luolingchun** [comment]
@samuelhwilliams Thanks for your attention, possible plans for early September.

**Comment by awoimbee** [comment]
Hi, [autodoc_pydantic](https://github.com/mansenfranzen/autodoc_pydantic) had to be updated too, maybe this PR could help you along the way: https://github.com/mansenfranzen/autodoc_pydantic/pull/160/files

**Comment by CostcoFanboy** [comment]
Why drop Python 3.7 support? 🤔 

There is only 2 dependencies in this project:
- Flask 2.3.2 still has [Python 3.7](https://flask.palletsprojects.com/en/2.3.x/installation/#python-version) support
- [Pydantic v2](https://pypi.org/project/pydantic/) still has Python 3.7 support

I don't see anything that was deprecated that would make us have to drop support in Python patch notes either.

Is it because of the Python Software Foundation EOL? Otherwise it seems arbitrary and unneeded.

**Comment by samuelhwilliams** [comment]
@luolingchun would you like any help with the work to get ready for v3.0? If I get some free time, I could look at deprecating some of those parameters/classes?

**Comment by luolingchun** [comment]
@CostcoFanboy [Flask 2.3.0](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0) has dropped support for python 3.7, so we don't have to support the old python version all the time.

**Comment by luolingchun** [comment]
@samuelhwilliams Thanks, you can do [Upgrade openapi 3.1.0](#93) if you want.

You need to submit a PR to the v3.x branch.

**Comment by samuelhwilliams** [comment]
Would you consider releasing a new version that just has the pydantic v2 changes pulled in? They would be really useful for me at the moment, and it would be great to be able to start using that without having to wait for the other changes (which in my case aren't as valuable).

Of course it is your call, so just asking :)

**Comment by luolingchun** [comment]
@samuelhwilliams I released a beta version the other day, but what I want you to know is that I won't fix issues for this release, and I'm not going to change my release schedule.
