### ISSUE TITLE
Add ability to disable other sources of documentation

### ISSUE THREAD

**Issue by CostcoFanboy** [luolingchun/flask-openapi3#77]
It would be nice if we could exclude certain documentation from running and having the choice of having no prefix.

e.g.
I only want swagger and I want it to be on url path /docs from root.

**Comment by luolingchun** [comment]
You can use `redirect` to achieve what you want.

```python
app = OpenAPI(__name__)

@app.route("/")
def index():
    return redirect(url_for("openapi.openapi"))


@app.route("/docs")
def swagger():
    return redirect(url_for("openapi.swagger"))
```

By the way, `app.url_map` can obtain all available endpoints.

```
Map([<Rule '/static/<filename>' (GET, OPTIONS, HEAD) -> static>,
 <Rule '/openapi/static/<filename>' (GET, OPTIONS, HEAD) -> openapi.static>,
 <Rule '/openapi/openapi.json' (GET, OPTIONS, HEAD) -> openapi.api_doc>,
 <Rule '/openapi/swagger' (GET, OPTIONS, HEAD) -> openapi.swagger>,
 <Rule '/openapi/redoc' (GET, OPTIONS, HEAD) -> openapi.redoc>,
 <Rule '/openapi/rapidoc' (GET, OPTIONS, HEAD) -> openapi.rapidoc>,
 <Rule '/openapi/' (GET, OPTIONS, HEAD) -> openapi.openapi>,
 ...
```

**Comment by CostcoFanboy** [comment]
Got it, I was seeking a bit more of an elegant solution that would not maybe trigger 300s.
Would you be open to a PR to at least not run the 2 other services if the user chooses so?

**Comment by luolingchun** [comment]
Welcome PR, but there should be no breaking updates.
