### ISSUE TITLE
Parameters in blueprint `url_prefix`

### ISSUE THREAD

**Issue by riedgar-ms** [luolingchun/flask-openapi3#82]
I may be missing something obvious with this, however: in 'regular' Flask, I can put a parameter in a URL prefix, and have something like:
```python
project_bp= Blueprint(
    "project", __name__, url_prefix="/projects/<project_name>"
)

@project_bp.route("/")
def index(project_name: str):
    logger.info(f"Called GET for project {project_name}")


tag_bp = Blueprint("tag", _name__, url_prefix="/tags")

@route("/")
def index(project_name: str):
    logger.info(f"Called GET tags for {project_name}")

project_bp.register_blueprint(tag_bp)
```
The net result of this being that both `/project/<name>` and `/project/<name>/tags` would end up as routes. Everything in the `tag_bp` automatically gets supplied with the `project_name` argument.

I'm trying to do something similar with `flask-openapi3` but it's not quite working. I'm not yet nesting, but
```python
api = APIBlueprint(
    "project",
    __name__,
    url_prefix="/project/<name>",
    abp_tags=[Tag(name="project_tag", description="Some project API")],
    # disable openapi UI
    doc_ui=True,
)

@api.get(rule="/", responses={"200": Project})
def get_project(path: ProjectPath) -> Project:
    _logger.info(f"Called get_project with {path}")
    result = Project(name=path.name, description="No description set")
    return result.json()
```
doesn't work - the `path` argument is always set to `<name>`. To get it to function as I want, I have to define things like this:
```python
api = APIBlueprint(
    "project",
    __name__,
    url_prefix="/project/",
    abp_tags=[Tag(name="project_tag", description="Some project API")],
    # disable openapi UI
    doc_ui=True,
)

@api.get(rule="/<name>", responses={"200": Project})
def get_project(path: ProjectPath) -> Project:
    _logger.info(f"Called get_project with {path}")
    result = Project(name=path.name, description="No description set")
    return result.json()
```
If I then try nesting this, I'm not going to be able to 'collect up' the parameters from higher up in the blueprint hierarchy.... I have a feeling I'm missing something.

Thanks in advance.

**Comment by luolingchun** [comment]
Thanks @riedgar-ms  for reporting this. I can confirm this bug.
