### ISSUE TITLE
可否新增直接响应orm对象

### ISSUE THREAD

**Issue by kanhebei** [luolingchun/flask-openapi3#96]
from pydantic import BaseModel
from flask_openapi3.openapi import OpenAPI
from flask_openapi3.blueprint import APIBlueprint
from flask_openapi3.models import Tag, Info

app = OpenAPI(__name__, info=Info(title='book API', version='1.0.0'))

api = APIBlueprint('api', __name__, url_prefix='/api')

class HelloSchema(BaseModel):
    msg: str = 'success'
    title: str

    class Config:
        orm_mode = True

class HelloModel:
    title: str = 'world'

    @classmethod
    def get_first(cls):
        return cls()

@api.get('/hello', responses={200: HelloSchema})
def hello():
    # 直接返回orm实例
    return HelloModel.get_first()

app.register_api(api)

if __name__ == '__main__':
    app.run(debug=True)

**Comment by kanhebei** [comment]
视图函数可以直接返回一个sqlalchemy model的实例

return db.get_or_404(Product, pk)

**Comment by luolingchun** [comment]
不考虑支持，sqlalchemy model序列化是一个用户自定义个过程，我们不能主观定义一个固定的序列化结果。
